"""
Consider all integer combinations of ab for 2  a  5 and 2  b  5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?
"""
import math

def root(m, n):
    x = 1
    while(x**n < m):
        x = x + 1
    return x

d = {}
l = []
fd = {}
for i in range(2, 100+1):
    j = i**2
    c = 2
    while(100 >= j):
        if(not(j in d)):
            d[j] = c
        j = j * i
        c = c + 1
    fd[i] = set([])

for i in range(2, 100+1):
    if(not(i in d)):
        for j in range(2, 100+1):
            fd[i].add(j)
    else:
        r = root(i, d[i])
        for j in range(2, 100+1):
            fd[r].add(j*d[i])

res = 0
ts = []
for i in range(2, 100+1):
    res = res + len(fd[i])
print(res)


s = set([])
for a in range(2, 100+1):
    for b in range(2, 100+1):
        s.add(a**b)

print(len(s))
