"""
Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk  Pj| is minimised; what is the value of D?
"""
import math

def p(n):
    return(int(n*(3*n-1)/2))

def isP(k):
    n = (math.sqrt(24*k+1)+1)/6
    return(n == int(n))

tot = 0
diff = 0
d = 0
i = 0
mini = 0
while((0 == d)or(d <= mini)):
    i = i + 1
    j = 1
    while((d <= diff)and(j < i)):
        tot = p(i) + p(i-j)
        diff = p(i) - p(i-j)
        if(1 == j):
            mini = diff
        if((isP(tot))and(isP(diff))and((0 == d)or((0 != d)and(diff < d)))):
            d = diff
        j = j + 1
print(d)
