"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import math

def t(n):
    return(int((n+1)*n/2))
def p(n):
    return(int((3*n-1)*n/2))
def h(n):
    return((2*n-1)*n)

def isT(x):
    n = (math.sqrt(8*x+1)-1)/2
    return(n == int(n))
def isP(x):
    n = (math.sqrt(24*x+1)+1)/6
    return(n == int(n))
def isH(x):
    n = (math.sqrt(8*x+1)+1)/4
    return(n == int(n))

i = 144
while(not((isT(h(i)))and(isP(h(i))))):
    i = i + 1
print(h(i))
