"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.

"""
def feb(i):
    if (i <= 1):
        return 1
    else:
        return (feb(i-2)+feb(i-1))

i = 0
sum = 0
n = feb(i)
while (n < 4000000):
    print (i)
    i = i + 1
    if (0 == n % 2):
        sum = sum + n
    n = feb (i)

print (sum)
